% filename = '../data/measurement/pControlAnkelLR7.txt';
filename = '../data/measurement/pControlKnee7.txt';
data = load(filename);
numSamples = size(data, 1);
t = data(:, 1) / 1000.0;
goalPos = data(:, 2) * 0.29 / 360 * pi;
currentPos = data(:, 3) * 0.29 / 360 * pi;
figure;
plot(t, goalPos, t, currentPos);
xlim([0, 10]);
acc = computeAcc(currentPos, t);
speed = computeSpeed(currentPos, t);
speed = speed(1:numSamples-2);
err = goalPos(2:numSamples) - currentPos(1:numSamples-1);
err = err * 100;
err = err(1:numSamples - 2);
figure;
% plot(t(2:numSamples-1), err, t(2:numSamples-1), speed, t(2:numSamples-1), acc);
plot(t(2:numSamples-1), err, t(2:numSamples-1), speed);
xlim([0, 10]);
